### ISSUE TITLE
Incorrect SHA-2 output with Bristol Fashion circuit

### ISSUE THREAD

**Issue by mskd12** [emp-toolkit/emp-tool#106]
If F(st, msg) is the compression function of SHA-2, we are computing F(0, 0). The expected output is `7ca51614425c3ba8ce54dd2fc2020ae7b6e574d198136d0fae7e26ccbf0be7a6` but the below circuit outputs `65E7D0FD33647E75F0B6C8198B2EA76DE7504043F4BB2A7315DC3A422868A53E` 

(Tested with the current master `53be447e972b8436b2c0a12e25c460d2665d869f`)

```
#include "emp-tool/emp-tool.h"

// expected out: 7ca51614425c3ba8ce54dd2fc2020ae7b6e574d198136d0fae7e26ccbf0be7a6
void sha2_check() {
    emp::Integer inp(512 + 256, 0, emp::ALICE);

    emp::Integer out(256, 0, emp::PUBLIC);

    std::string filepath = "/usr/local/include/emp-tool/circuits/files/bristol_fashion/sha256.txt";
    emp::BristolFashion cf(filepath.c_str());
    cf.compute(out.bits.data(), inp.bits.data());
    std::cout << out.reveal<std::string>() << std::endl;
}

int main(int argc, char** argv) {
	emp::setup_plain_prot(false, "tmp.txt");
    sha2_check();
	emp::finalize_plain_prot();
}
```

**Comment by mskd12** [comment]
So apparently Bristol Fashion circuits reverse bit order. 

7 = 0111 reversed is 1110 = E 
c = 1100 reversed is 0011 = 3

Similarly, `7ca51614425c3ba8ce54dd2fc2020ae7b6e574d198136d0fae7e26ccbf0be7a6` reversed is `65E7D0FD33647E75F0B6C8198B2EA76DE7504043F4BB2A7315DC3A422868A53E`.

**Comment by gitCoder1024** [comment]
I don't know how to correspond the  bits of the input value to the input line,  have you got the right answer ?
