### ISSUE TITLE
There are many warnings when compile this library.

### ISSUE THREAD

**Issue by locomotive-crypto** [emp-toolkit/emp-tool#107]
When I was compiling this library, It shows many warnings. But it can build successfuly.

Now I report to you and hope you can solve it.

`locomotive@locomotive-VirtualBox:~/emp/emp-tool-master/build$ make

Scanning dependencies of target emp-tool

[  3%] Building CXX object CMakeFiles/emp-tool.dir/emp-tool/emp-tool.cpp.o
[  7%] Linking CXX shared library libemp-tool.so
[  7%] Built target emp-tool
Scanning dependencies of target netio
[ 10%] Building CXX object CMakeFiles/netio.dir/test/netio.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/netio.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
In file included from /usr/include/string.h:494:0,
                 from /usr/include/c++/7/cstring:42,
                 from /home/locomotive/emp/emp-tool-master/emp-tool/utils/block.h:23,
                 from /home/locomotive/emp/emp-tool-master/emp-tool/io/io_channel.h:3,
                 from /home/locomotive/emp/emp-tool-master/emp-tool/io/file_io_channel.h:5,
                 from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:2,
                 from /home/locomotive/emp/emp-tool-master/test/netio.cpp:1:
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void emp::RecverSubChannel::recv_data(void*, int)’ at /home/locomotive/emp/emp-tool-master/emp-tool/io/highspeed_net_io_channel.h:97:10,
    inlined from ‘void emp::HighSpeedNetIO::recv_data_internal(void*, int)’ at /home/locomotive/emp/emp-tool-master/emp-tool/io/highspeed_net_io_channel.h:247:22,
    inlined from ‘void emp::IOChannel<T>::recv_bool(bool*, int) [with T = emp::HighSpeedNetIO]’ at /home/locomotive/emp/emp-tool-master/emp-tool/io/io_channel.h:18:3:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:71: warning: ‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’: specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
                                                                       ^
[ 14%] Linking CXX executable bin/netio
[ 14%] Built target netio
Scanning dependencies of target prp
[ 17%] Building CXX object CMakeFiles/prp.dir/test/prp.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/prp.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[ 21%] Linking CXX executable bin/prp
[ 21%] Built target prp
Scanning dependencies of target int
[ 25%] Building CXX object CMakeFiles/int.dir/test/int.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/int.cpp:2:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[ 28%] Linking CXX executable bin/int
[ 28%] Built target int
Scanning dependencies of target hash
[ 32%] Building CXX object CMakeFiles/hash.dir/test/hash.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/hash.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[ 35%] Linking CXX executable bin/hash
[ 35%] Built target hash
Scanning dependencies of target garble
[ 39%] Building CXX object CMakeFiles/garble.dir/test/garble.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/garble.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h: In constructor ‘emp::BristolFormat::BristolFormat(const char*)’:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:23:3: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
   (void)fscanf(f, "%d%d\n", &num_gate, &num_wire);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:24:3: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
   (void)fscanf(f, "%d%d%d\n", &n1, &n2, &n3);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:25:3: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
   (void)fscanf(f, "\n");
   ^~~~~~~~~~~~~~~~~~~~~
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:30:4: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
    (void)fscanf(f, "%d", &tmp);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:32:5: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     (void)fscanf(f, "%d%d%d%d%s", &tmp, &gates[4*i], &gates[4*i+1], &gates[4*i+2], str);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:37:5: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     (void)fscanf(f, "%d%d%d%s", &tmp, &gates[4*i], &gates[4*i+2], str);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 42%] Linking CXX executable bin/garble
[ 42%] Built target garble
Scanning dependencies of target f2k
[ 46%] Building CXX object CMakeFiles/f2k.dir/test/f2k.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/f2k.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[ 50%] Linking CXX executable bin/f2k
[ 50%] Built target f2k
Scanning dependencies of target netio2
[ 53%] Building CXX object CMakeFiles/netio2.dir/test/netio2.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/netio2.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[ 57%] Linking CXX executable bin/netio2
[ 57%] Built target netio2
Scanning dependencies of target gen_circuit
[ 60%] Building CXX object CMakeFiles/gen_circuit.dir/test/gen_circuit.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/gen_circuit.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[ 64%] Linking CXX executable bin/gen_circuit
[ 64%] Built target gen_circuit
Scanning dependencies of target prg
[ 67%] Building CXX object CMakeFiles/prg.dir/test/prg.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/prg.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[ 71%] Linking CXX executable bin/prg
[ 71%] Built target prg
Scanning dependencies of target bit
[ 75%] Building CXX object CMakeFiles/bit.dir/test/bit.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/bit.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[ 78%] Linking CXX executable bin/bit
[ 78%] Built target bit
Scanning dependencies of target ecc
[ 82%] Building CXX object CMakeFiles/ecc.dir/test/ecc.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/ecc.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[ 85%] Linking CXX executable bin/ecc
[ 85%] Built target ecc
Scanning dependencies of target mitccrh
[ 89%] Building CXX object CMakeFiles/mitccrh.dir/test/mitccrh.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/mitccrh.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[ 92%] Linking CXX executable bin/mitccrh
[ 92%] Built target mitccrh
Scanning dependencies of target halfgate
[ 96%] Building CXX object CMakeFiles/halfgate.dir/test/halfgate.cpp.o
In file included from /home/locomotive/emp/emp-tool-master/emp-tool/emp-tool.h:10:0,
                 from /home/locomotive/emp/emp-tool-master/test/halfgate.cpp:1:
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:19:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
/home/locomotive/emp/emp-tool-master/emp-tool/circuits/circuit_file.h:68:14: warning: ignoring attributes on template argument ‘emp::block {aka __vector(2) long long int}’ [-Wignored-attributes]
  vector<block> wires;
              ^
[100%] Linking CXX executable bin/halfgate
[100%] Built target halfgate`

**Comment by locomotive-crypto** [comment]
The compiler that I used is as following:
`$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

**Comment by wangxiao1254** [comment]
I think most of them cannot be eliminated elegantly. For example, some errors are related to using __m128i with vector. While others are actually gcc bug AFAIK.

**Comment by locomotive-crypto** [comment]
Thanks for your reply.
