### ISSUE TITLE
The example for Pseudorandom permutation is incorrect!

### ISSUE THREAD

**Issue by locomotive-crypto** [emp-toolkit/emp-tool#108]
The example showed in the README.md is incorrect: https://github.com/emp-toolkit/emp-tool#pseudorandom-permutation .

 The wrong code is as following:

`block key;
PRG().random_block(&key,1);
PRP prp(&key);`

You can see the definition of `PRP` and it takes a `const block&` type as parameter.

`PRP(const block& key)`

Here, you give a pointer to `const block` type.

**Comment by wangxiao1254** [comment]
fixed

**Comment by locomotive-crypto** [comment]
OK.
