### ISSUE TITLE
How to understand circuit file?

### ISSUE THREAD

**Issue by locomotive-crypto** [emp-toolkit/emp-tool#111]
I modify the example code in gen_circuit.cpp(https://github.com/emp-toolkit/emp-tool/blob/master/test/gen_circuit.cpp) to generate binary circuit file. But I don't understand it.

My program for generating circuit file is as following:
```
void ham(int n) {
   Integer a(n, 114, ALICE);
   Integer b(n, 81, BOB);
   Integer c = a^b;
   Integer d = c.hamming_weight();
   d.reveal<string>();
}
int main(int argc, char** argv) {
   setup_plain_prot(true, "sort.txt");
   ham(2);
   finalize_plain_prot ();
}
```

After run this pargam, it generates a file, named `sort.txt`.

Running command `cat ./sort.txt`, it shows as following:

```
5 9
2 2 2
                                                                                                                                                                                              
2 1 0 2 4 XOR
2 1 1 3 5 XOR
2 1 0 0 6 XOR
2 1 6 4 7 XOR
2 1 6 5 8 XOR

```

Could you explain it line by line?

Thanks in advance.

**Comment by wangxiao1254** [comment]
Explanation of the circuit file can be found at: https://homes.esat.kuleuven.be/~nsmart/MPC/old-circuits.html

**Comment by locomotive-crypto** [comment]
Thanks!
