### ISSUE TITLE
Support for boost::multiprecision::uint128_t and uint256_t?

### ISSUE THREAD

**Issue by rdeviti** [emp-toolkit/emp-tool#113]
For some applications, it might be useful to support `uint128_t` and `uint256_t`. Do you plan to add such extensions? 
Currently, the `emp::Integer` constructor works with inputs of type `int64_t`. Unless I'm missing something, I think all that would be needed is to include `<boost/multiprecision/cpp_int.hpp>` in `circuits/integer.h` and `utils/utils.h`, and add a specific constructor for each type. Or, is it the case that you wouldn't like to rely on Boost C++ libraries?

**Comment by wangxiao1254** [comment]
I would not want to include any more dependency unless absolutely necessary. If you need uint128_t, you could just create two Integer each from a uin64_t and append them together? I can add interfaces for easy concatenation of Integers.

**Comment by rdeviti** [comment]
Makes sense. I thought using Boost would have been faster, e.g., to adapt a `reveal`, or to use`int_to_bool` as is. But, indeed, I realise that including more dependencies isn't great. Sure, adding interfaces for concatenation would be nice, thanks! (Just to make sure, the v0.1 Integer constructor that'd call `bool_data` on an input string is deprecated, right?)

**Comment by wangxiao1254** [comment]
yep, there was a version that actually initialize the Integer based on gmp, but I got rid of gmp too :)

**Comment by wangxiao1254** [comment]
BTW, I think there is a __uint128_t in both gcc and clang. I could add that too.

**Comment by rdeviti** [comment]
I think Isaac's PR solves this issue as well, so I can close this!
