### ISSUE TITLE
Make `prot_exec` and `circ_exec` non-static

### ISSUE THREAD

**Issue by Isweet** [emp-toolkit/emp-tool#117]
I am accessing EMP via an FFI, and I would like to be able to launch multiple sessions of EMP from one process. Unfortunately, since `prot_exec` and `circ_exec` are static, this won't work.

I think that if the circuits were modified to instead take as an argument the protocol / circuit execution then this would be possible.

For example:

1. Modify `Bit::reveal` (https://github.com/emp-toolkit/emp-tool/blob/master/emp-tool/circuits/bit.hpp#L22) to take a `ProtocolExecution *` as an additional argument. Call `->reveal` on the argument.
2. When initializing semi-honest, return an object containing the protocol execution and circuit execution. Later calls to `Bit::reveal` etc. will then pass the `ProtocolExecution` that was returned from setting up the semihonest protocol.
https://github.com/emp-toolkit/emp-sh2pc/blob/master/emp-sh2pc/semihonest.h#L12

Hope this makes sense. Let me know what you think!

**Comment by wangxiao1254** [comment]
This would require a complete rewrite of EMP. In particular, all operator overloading will no longer be possible. I'm not sure if this will happen in the main repo but you are welcome to make this change in your fork.

**Comment by Isweet** [comment]
What if the EMP types contained a reference to the appropriate ProtocolExecution and CircuitExecution? In other words,

```
inline Bit Bit::operator &(const Bit& rhs) const{
	Bit res;
        assert (this->circ_exec == rhs->circ_exec); // we expect both sides to have identical references
	res.bit = this->circ_exec->and_gate(bit, rhs.bit);
	return res;
}
```

**Comment by wangxiao1254** [comment]
This would mean that this pointer has be to duplicated for every EMP object down to the bit level. runtime slowdown and memory overhead

**Comment by Isweet** [comment]
Good point. Okay, I'll fork and write my own non-overloaded versions of the circuits.

**Comment by wangxiao1254** [comment]
As you san see, the current code support multi-threading and each thread would contain their own pointer. If you can have your sessions all run in different threads, that would work too.

**Comment by Isweet** [comment]
Input step meaning [`feed`](https://github.com/emp-toolkit/emp-sh2pc/blob/master/emp-sh2pc/sh_gen.h#L28)?

**Comment by wangxiao1254** [comment]
yes. It is not hard to be made multi-thread, but we just didn't find a case to do so:)
