### ISSUE TITLE
运行命令如何使用

### ISSUE THREAD

**Issue by GGC1** [emp-toolkit/emp-tool#118]
我自己的总结：./bin/ferret 1 12345 logn & ./bin/ferret 2 12345 logn
适用于任何文件的运行，可以运行tool的也可以是ot，sh2pc的
我想知道这是什么原因
![image](https://user-images.githubusercontent.com/41094111/114819006-4ed10d80-9def-11eb-8d52-6ab2e2b81a4f.png)

**Comment by GGC1** [comment]
新手求教

**Comment by wangxiao1254** [comment]
Please take a look at the source file. It if self explainable once you see the test file.
