### ISSUE TITLE
刚更新的tool安装时报错

### ISSUE THREAD

**Issue by GGC1** [emp-toolkit/emp-tool#122]
![image](https://user-images.githubusercontent.com/41094111/115253094-a1e3f100-a15e-11eb-93b3-128796c6ff21.png)
更新的工具安装报错
![image](https://user-images.githubusercontent.com/41094111/115255664-13bd3a00-a161-11eb-8aee-8a1b68abffab.png)
我发现在test文件夹下没有sha_256.cpp.o文件
不知道为什么

**Comment by GGC1** [comment]
![image](https://user-images.githubusercontent.com/41094111/115257184-6b0fda00-a162-11eb-971f-42b0000314b8.png)
![image](https://user-images.githubusercontent.com/41094111/115257346-95fa2e00-a162-11eb-8cdf-dfecf1b7ca7e.png)
![image](https://user-images.githubusercontent.com/41094111/115257462-b0cca280-a162-11eb-986e-3e2a6926c848.png)
就是这种报错

**Comment by wangxiao1254** [comment]
make sure your openssl is the latest version.

**Comment by GGC1** [comment]
谢谢，升级openssl之后解决了。

**Comment by GGC1** [comment]
但是我有个疑问，从上面的报错中我找不到是因为openssl未升级造成的。你是如何解决的。

**Comment by wangxiao1254** [comment]
Great!. I searched "evp_sha3_256"
