### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by GGC1** [emp-toolkit/emp-tool#130]
编译的时候用了-ENABLE=on，报未定义引用错误，找半天错误没找到。
![图片](https://user-images.githubusercontent.com/41094111/119754378-fc493d80-bed2-11eb-8b6b-ec995ff836ef.png)

**Comment by carlweng** [comment]
In the ./emp-tool/ directory,

cmake  -DENABLE_FLOAT=ON .
make -j4
bin/test_float

**Comment by GGC1** [comment]
thank you,success!
