### ISSUE TITLE
g++ compile error

### ISSUE THREAD

**Issue by tomato990** [emp-toolkit/emp-tool#131]
What is the version of g++ shall I use? I have a compiling error when running the make file. Here is the capture.
(Seems the sha3_256 requires parameters but the code does not feed one).

![image](https://user-images.githubusercontent.com/9076241/121500419-44289400-c9ac-11eb-9568-96ce2fbd01d3.png)

**Comment by wangxiao1254** [comment]
Please upgrade your openssl lib.

**Comment by tomato990** [comment]
I am still facing the same error. 
The openssl I am using is openssl1.1.1k (should be the latest version)
![image](https://user-images.githubusercontent.com/9076241/121544991-1eb17f80-c9d8-11eb-8e53-63dd3a7ad596.png)

**Comment by wangxiao1254** [comment]
Our github action checks use  version 9.3, I think something earlier should work too: https://github.com/emp-toolkit/emp-tool/runs/2635525131?check_suite_focus=true

**Comment by tomato990** [comment]
The problem still exists for my ubuntu machine. (but not on my Macbook)
I found someone facing the same problem here. https://githubmemory.com/repo/MPC-SoK/frameworks/issues/49
I guess it's because the new g++ compiler does not accept the non-parameter template.

**Comment by tomato990** [comment]
Solved by changing EVP_sha3_256() to EVP_sha256().
