### ISSUE TITLE
Is there an efficient way to find out the relationship between wires indexes and emp::Integer in the circuit generated by EMP-TOOLKIT?

### ISSUE THREAD

**Issue by gconeice** [emp-toolkit/emp-tool#132]
Hi,

Really nice to e-meet you!

Recently, I am trying to use EMP-TOOLKIT to generate some bristol format circuits and evaluate these circuits in EMP-MPC. However, my test shows that the EMP-MPC outputs are incorrect and I suddenly realize that it is caused by my wrong way to set input wire values. For example,

First, I generate a simply two (in my real application, there will be more) millionaires problem circuit (both inputs known by Alice) as follow:

```
using Circuit = emp::BristolFormat;
{
    emp::setup_plain_prot(true, FILENAME);
    emp::Integer a {2, 0, emp::ALICE};
    emp::Integer b {2, 0, emp::ALICE};
    emp::Bit cond1 = (b > a);
    cond1.reveal<bool>();
    emp::finalize_plain_prot();
}
```

Then I evaluate the output circuit in EMP-MPC to get the truth table and my evaluation shows that:

- a = in[3]*2 + in[0]
- b = in[1]*2 + in[2]

where in[0..3] are four input wires, which is different from what I thought it would be as:

- a = in[3]*2 + in[2]
- b = in[1]*2 + in[0]

or somthing similar to this.

Therefore, I am wondering if there is an efficient way for me to generate the circuit in EMP-TOOLKIT so I can know the way to parse wires to corresponding emp::Integer. Or if I can output something while generating the circuits to explicitly show this relationship.

Thank you very much!

**Comment by wangxiao1254** [comment]
One way that you can know the id of each wire is to cast the block into an array of uint64_t. the higher int is the id.
See e.g.: https://github.com/emp-toolkit/emp-tool/blob/master/emp-tool/execution/plain_circ.h#L65

**Comment by wangxiao1254** [comment]
On a second examination, I think the wires should all be ordered as one would expect rather than the order you mentioned above. Can you double-check? :)

**Comment by gconeice** [comment]
Hi. Thank you very much for your reply!

I retried to generate the circuit but it still not works as my expectation. Specifically, the program I executed is as follow:

```
#include <emp-tool/execution/plain_prot.h>
#include <emp-sh2pc/emp-sh2pc.h>
#include <emp-tool/circuits/bit.h>
#include <emp-tool/circuits/circuit_file.h>

#include <iostream>

static const char* FILENAME = "test.txt";

int main() {
  using Circuit = emp::BristolFormat;
  {
    emp::setup_plain_prot(true, FILENAME);
    emp::Integer a {2, 0, emp::ALICE};
    emp::Integer b {2, 0, emp::ALICE};
    emp::Bit cond1 = (b > a);
    cond1.reveal<bool>();
    emp::finalize_plain_prot();	  
  }
}
```

The test.txt will be:

```
13 17
4 0 1
                                                                                                                                                                                            
2 1 0 2 4 XOR
2 1 4 2 5 AND
2 1 1 3 6 XOR
2 1 5 3 7 XOR
2 1 6 5 8 XOR
2 1 6 7 9 AND
2 1 5 9 10 XOR
2 1 1 3 11 XOR
2 1 11 10 12 XOR
1 1 12 13 INV
1 1 13 14 INV
2 1 0 0 15 XOR
2 1 15 14 16 XOR
```

I tried to set in[0..3] and see out[16], for example:

in[0..3] := 1000 ---> out[16] = 0
in[0..3] := 0100 ---> out[16] = 1
in[0..3] := 0010 ---> out[16] = 1
in[0..3] := 0001 ---> out[16] = 0

which means in[0] and in[3] belong to **emp::Integer a** && in[1] and in[2] belong to **emp::Integer b**.

**Comment by wangxiao1254** [comment]
little-endian or big-endian in your representation? Try 0011 :)

**Comment by gconeice** [comment]
Hi!

in[0..3] := 1000 <——> in[0] := 1, in[1] := 0, in[2] := 0, in[3] := 0

Therefore, 0011 will result in 0.

**Comment by wangxiao1254** [comment]
Please try this example

  setup_plain_prot(true, "sort.txt");
   Integer a(2,0,ALICE);
   Integer b(2,0,ALICE);
   (a[0] & b[0]).reveal();

You will see that the output circuit is
3 7
4 0 1

2 1 0 2 4 AND
2 1 0 0 5 XOR
2 1 5 4 6 XOR

Here only wire 0 and 2 are used. This is because 0 is for a[0] and 2 is for b[0].

**Comment by gconeice** [comment]
Thank you very much! I tried your example (with a[0]&a[1], a[0]&b[1] ...). It indeed works.

The experiment shows that a[0] := in[0], a[1] := in[1], b[0] := in[2] and b[1] := in[3].

Then, there must be some problem in (b > a) circuit generating procedure. Let's set 
a[0] = in[0] := 0
a[1] = in[1] := 1
b[0] = in[2] := 0
b[1] = in[3] := 0

(b > a) should be 0, obviously.

However, based on the BF circuit in my previous reply, which is:

```
13 17
4 0 1
                                                                                                                                                                                            
2 1 0 2 4 XOR
2 1 4 2 5 AND
2 1 1 3 6 XOR
2 1 5 3 7 XOR
2 1 6 5 8 XOR
2 1 6 7 9 AND
2 1 5 9 10 XOR
2 1 1 3 11 XOR
2 1 11 10 12 XOR
1 1 12 13 INV
1 1 13 14 INV
2 1 0 0 15 XOR
2 1 15 14 16 XOR
```

The entire calculation process will be:

```
wire[0] = 0
wire[1] = 1
wire[2] = 0
wire[3] = 0
wire[4] = wire[0] XOR wire[2] = 0
wire[5] = wire[4] AND wire[2] = 0
wire[6] = wire[1] XOR wire[3] = 1
wire[7] = wire[5] XOR wire[3] = 0
wire[8] = wire[6] XOR wire[5] = 1
wire[9] = wire[6] AND wire[7] = 0
wire[10] = wire[5] XOR wire[9] = 0
wire[11] = wire[1] XOR wire[3] = 1
wire[12] = wire[10] XOR wire[11] = 1
wire[13] = INV wire[12] = 0
wire[14] = INV wire[13] = 1
wire[15] = wire[0] XOR wire[0] = 0
wire[16] = wire[14] XOR wire[15] = 1, which is wrong.
```

**Comment by wangxiao1254** [comment]
actually, the comparison assumes signed input. so if the highest bit is 1. it is a negative number.

**Comment by gconeice** [comment]
Oops, I also realized this problem after going into integer.hpp source code just now. Thank you very much for your kindly help! Sorry for causing troubles.

**Comment by wangxiao1254** [comment]
np. closing the issue.
