### ISSUE TITLE
trouble understanding NetIO code

### ISSUE THREAD

**Issue by themighty1** [emp-toolkit/emp-tool#135]
Hi, I'm trying to port the NetIO code and I can't understand what this line does
https://github.com/emp-toolkit/emp-tool/blob/1345a1462b12fd41fa2f02bd603b6e8067caf53d/emp-tool/io/net_io_channel.h#L32
Why is it `this->port `when port is not a pointer? and what is the purpose of `& 0xFFFF` ?
Thank you.

**Comment by carlweng** [comment]
For the `this` pointer, please refer to c++ [this keyword](https://en.cppreference.com/w/cpp/language/this).

For `port & 0xFFFF`, I guess it is to prevent someone from accidentally input a port number greater than 65535 for test, since that is the largest port number.

**Comment by themighty1** [comment]
thanks, this helps.
