### ISSUE TITLE
Ability to marshall session state to disk.

### ISSUE THREAD

**Issue by themighty1** [emp-toolkit/emp-tool#139]
Hi, would it be possible to perform the offline phase of ag2pc and then marshall the state to disk. Then at some future time, the data can be unmarshalled to resume the online phase.

I looked around the emp-tool's code, I didn't find anything which suggests that it is possible. Now, I'm ok with implementing the marshalling myself, I just don't want to reinvent the wheel.
I'd be thankful if you could confirm whether such functionality already exists.

**Comment by wangxiao1254** [comment]
you can store the state to the disk but it is not really written right now. There is a class https://github.com/emp-toolkit/emp-tool/blob/master/emp-tool/io/file_io_channel.h that you might find helpful.
