### ISSUE TITLE
how to run netio test?

### ISSUE THREAD

**Issue by AdijeShen** [emp-toolkit/emp-tool#143]
![image](https://user-images.githubusercontent.com/16702475/144807183-f2feb18e-178e-42d0-91a1-c2cd5e1429b7.png)
![image](https://user-images.githubusercontent.com/16702475/144807347-b6061f98-3bb9-4141-a839-4e59f7640dbc.png)

I've tried to run two consoles with respect to ALICE and BOB, but they stuck after printing "NetIO".

**Comment by Yann-lyy** [comment]
Make the port of two commands to be the same.
`.../bin/test_netio 1 3331` for Alice.
`.../bin/test_netio 2 3331` for Bob.
Or to use 
'./run ./bin/test_netio'

**Comment by AdijeShen** [comment]
@Yann-lyy Thanks a lot for your reply! I succeed with both methods.
