### ISSUE TITLE
Unused `con` in `AES_opt_key_schedule`

### ISSUE THREAD

**Issue by tsunrise** [emp-toolkit/emp-tool#148]
Hello, 

It seems that in `aes_opt.h:AES_opt_key_schedule`, when generating the keys, there is an unused "shift left` instruction. Just wondering if this is a bug, or we can remove this call completely. 

https://github.com/emp-toolkit/emp-tool/blob/aaff3ab013861a8da3b11ade5fcab3a0655bf08d/emp-tool/utils/aes_opt.h#L53

Thanks!

**Comment by wangxiao1254** [comment]
Fixed! Thanks!

**Comment by wangxiao1254** [comment]
Also pushed a test case that the opt and normal routine produce the same key.
