### ISSUE TITLE
Using Salsa20 instead of AES for random permutation.

### ISSUE THREAD

**Issue by themighty1** [emp-toolkit/emp-tool#151]
Hi, @wangxiao1254, the recent paper GWKY20 showed us how to properly instantiate a hash function for half-gates garbling: with 2 calls to AES.

If we were to instantiate the hash function with fixed-key Salsa20 ( its inputs are 256-bit key + 128 bits of counter/nonce), we'd put the wire label into the last 128 bits and would borrow some of the bits of the key to put the tweak in there.
Thus we'd only have to make 1 call to Salsa20 instead of 2 calls to AES.

I don't have concreate numbers, but I read online that Salsa is only 20% slower that AESNI.
Doesn't this make Salsa a faster choice for random permutation? What are your thoughts on this?

**Comment by wangxiao1254** [comment]
I think a reanalysis is needed. The analysis for single-label hash function cannot be applied directly to double-label hash function AFAIK.

I'm also surprised that salsa is faster than AES. I suppose it didn't take AES-NI into consideration?

**Comment by themighty1** [comment]
So, DJB here claims that Salsa takes 4.25 cycles/byte https://cr.yp.to/streamciphers/why.html

**Comment by wangxiao1254** [comment]
When batched in 4 calls, AES-NI can do one permutation (128 bit) in ~11 cycles, so 11/16 cycles/byte. With appropriate batching, the computation is more like ECB than CBC.

**Comment by themighty1** [comment]
Thanks for bringing up the 11/16 number. 
It's also worth considering Salsa20/12. Here (https://cr.yp.to/snuffle.html) it shows 2.80 cycles/per byte for Salsa20/12.
But we are comparing 2 AES vs 1 Salsa to, so it's actually 22/16 vs 2.8.
(but the benchmark was done 10+ years ago on an old CPU. It should be faster on modern CPUs).

**Comment by themighty1** [comment]
nvm, I forgot that Salsa outputs 64 bytes out of which we only can use 16. So the actual ratio is 4x worse for Salsa.
