### ISSUE TITLE
Commitment functionality missing

### ISSUE THREAD

**Issue by MartinRenze** [emp-toolkit/emp-tool#158]
The "Commitment" described in the README is not in the code anymore. Has it been replaced? How can I use it?

It was in the `com.h` file. https://github.com/emp-toolkit/emp-tool/tree/0b5b25de122d09948b96a44bead7ad99b2a620df/emp-tool/utils

**Comment by wangxiao1254** [comment]
Yes this is deleted because the interface is not really very flexible and in many cases, we just want to use hash function directly anyway. I felt it is not that useful.

**Comment by MartinRenze** [comment]
thanks :)
