### ISSUE TITLE
Overflow in Interger::modExp implementation

### ISSUE THREAD

**Issue by supercrush** [emp-toolkit/emp-tool#159]
This implementation is not overflow-safe modular exponentiation since the Intermediate values of base * base can result in overflow and the intermediate result is truncated.
https://github.com/emp-toolkit/emp-tool/blob/44b1ddef7bf6bb8eefeede89f27084a96d1d349c/emp-tool/circuits/integer.hpp#L435
I think it would be better to take modular multiplication as a whole to avoid overflow. 

A simple test case could be n1 = 4, n2 = 4, a = 5, b =2, c = 2.
https://github.com/emp-toolkit/emp-tool/blob/44b1ddef7bf6bb8eefeede89f27084a96d1d349c/test/gen_circuit.cpp#L19

Hope this makes sense. Let me know what you think!

**Comment by wangxiao1254** [comment]
that's right. See line 429 of integer.hpp; is that what you mean?

**Comment by supercrush** [comment]
In my test case, the value of q, i.e., 2, is also less than half of the MAX_INT 15 (0x1111). However, base * base equals 25, which still overflows the MAX_INT and results in trucation.
