### ISSUE TITLE
Is it a bug in Hash class?

### ISSUE THREAD

**Issue by deadlywing** [emp-toolkit/emp-tool#166]
When I am looking the implement of Hash class, I notice the put method acts differently according to nbyte:
1. if exceeds maximum buffer size , do update once
2. if buffer can hold the data, then just copy data and do not update right now
3. else, in my thought, it should be doing update op with old data in buffer and renew both the buffer and size with new data. However,  the part of code I ref seems different, and I am confused.(If do update op with new data, then why copy the data to buffer?)

https://github.com/emp-toolkit/emp-tool/blob/e8a06ebea27983de4c0fd25e4a7345de4767c095/emp-tool/utils/hash.h#L32

**Comment by wangxiao1254** [comment]
Good point, it should be `EVP_DigestUpdate(mdctx, buffer, size);`

**Comment by deadlywing** [comment]
I think so. Thanks for replying so fast.
