### ISSUE TITLE
Conflict with C standard lib float.h

### ISSUE THREAD

**Issue by fabrice102** [emp-toolkit/emp-tool#18]
The file `float.h` conflicts with the C standard lib.

When using

```
find_package(emp-tool REQUIRED)
include_directories(${EMP-TOOL_INCLUDE_DIRS})
```

in a `CMakeLists.txt` file, the folder `/usr/local/include/emp-tool` gets added to the list of include directories. Because of that the following C++ program does not compile for example:

```
#include <gmpxx.h>

int main() {
}
```

(you can check without `cmake` via `g++ -I/usr/local/include/emp-tool program.cc`.)

I think a solution might be to only add `/usr/local/include` to the list of include directories instead of `/usr/local/include/emp-tool`.

But this issue might also arise inside `emp-tool` if ever the C standard lib `float.h` is used.

**Comment by wangxiao1254** [comment]
Oh this is bad. I think changing float.h to float_circuit.h can be a good option.

**Comment by wangxiao1254** [comment]
I think it should be fine now, although I still cannot run the example you have :)

I used `g++ -I/usr/local/include/emp-tool gg.cc --std=c++11` on ubuntu and it reported something related to gmp.

**Comment by fabrice102** [comment]
Thanks. I think however than moving all the headers in a common sub-folder `emp-tool` or `emp-toolkit` might be a good idea. Otherwise, other conflicts with libraries may arise. Almost all the libraries with many headers I have seen seems to do that. 

Actually I think that it is what Peter Rindal is doing in the branch master. So I guess your fix is a good temporary fix until you switch to the branch master.

**Comment by wangxiao1254** [comment]
ok I will probably organization files. But as you mentioned, it seems that even moving files still can cause potential problem right? if I use float.h  from C std lib.

Peter used a lot of virtual function which I cannot merge to the stable branch, but I'm trying to merge as much as possible for other parts.

**Comment by fabrice102** [comment]
If `emp-tool` itself uses `float.h` from the C std lib, you might indeed have an issue even after moving. So you may indeed also want to change `float.h` to `float_circuit.h`.

**Comment by fabrice102** [comment]
Actually, I think I said something wrong, you might not need to change `float.h` to `float_circuit.h` if you do not add the folders `utils` (or `emp-tool/utils`) in `include_directories` in `emp-tool`. Indeed, in that case, your `float.h` would be included by:

```C++
#include <emp-tool/utils/float.h>
// or if you are in the folder emp-tool/utils, you could also use
#include "float.h"
```

while the `float.h` std lib would be included by:

```C++
#include <float.h>
```

**Comment by wangxiao1254** [comment]
this should be fixed by now.
