### ISSUE TITLE
SHA3_256 and AES_128 tests do not work properly

### ISSUE THREAD

**Issue by AlvinKuruvilla** [emp-toolkit/emp-tool#183]
When running ```make install``` on the emp-tool it fails to compile with the following errors:

```
CMakeFiles/test_sha3_256.dir/sha3_256.cpp.o: In function `hash_in_circuit()':
sha3_256.cpp:(.text+0x77f): undefined reference to `emp_tool_circuits_files_bristol_fashion_Keccak_f_txt_len'
sha3_256.cpp:(.text+0x786): undefined reference to `emp_tool_circuits_files_bristol_fashion_Keccak_f_txt'
collect2: error: ld returned 1 exit status
```
There are also similar errors when trying to run the aes_238 test
Below I have provided a screenshot of the error for the sha3 test 
<img width="863" alt="image" src="https://user-images.githubusercontent.com/46870885/220789512-34516cc5-57a6-45f6-b744-9e9742afed5e.png">

**Comment by wangxiao1254** [comment]
did you enable `CRYPTO_IN_CIRCUIT`?

**Comment by AlvinKuruvilla** [comment]
Is that set through an environment variable? U am not very familiar with cmake unfortunately

**Comment by wangxiao1254** [comment]
Interesting. If the flag is not enabled, resulting makefile should not include the above test. can you provide details how you compile the code?

**Comment by AlvinKuruvilla** [comment]
Sorry, let me clarify. I wasn't sure how to set ```CRYPTO_IN_CIRCUIT```, so I removed the if check from the cmake file. That's when I ran into the error I screenshotted above. What is the proper way to set ```CRYPTO_IN_CIRCUIT```

**Comment by wangxiao1254** [comment]
oh I see. you should do `cmake -DCRYPTO_IN_CIRCUIT=True .` You may want to remove CMakeFiles and CMakeCache to force a total rebuild of cmake.

**Comment by AlvinKuruvilla** [comment]
Thank you for the help @wangxiao1254, I got it working correctly now. Would you accept a PR adding some documentation to the README about running these tests specifically?

**Comment by wangxiao1254** [comment]
Yes after cmake, you should run make which include producing the test.

Thanks! Thank would be great!
