### ISSUE TITLE
```f2k``` multiplication seems to mismatch operations

### ISSUE THREAD

**Issue by joerowell** [emp-toolkit/emp-tool#184]
Looking at the new implementation of [gfmul](https://github.com/emp-toolkit/emp-tool/blob/636b07de93027901705d4d7c2a263add882c2ce6/emp-tool/utils/f2k.h#L53) I've noticed that ```mul128```  seems to correspond to the early part of Figure 5 of [this](https://www.intel.com/content/dam/develop/public/us/en/documents/carry-less-multiplication-instruction.pdf), but the new ```gfmul``` implementation is actually part  of Figure 7 of [this](https://www.intel.com/content/dam/develop/public/us/en/documents/carry-less-multiplication-instruction.pdf).  

These are quite different. For example, Figure 5 of the Intel reference has this multiplication code:

```
__m128i tmp0, tmp1, tmp2, tmp3, tmp4, tmp5, tmp6, tmp7, tmp8, tmp9;
tmp3 = _mm_clmulepi64_si128(a, b, 0x00);
tmp4 = _mm_clmulepi64_si128(a, b, 0x10);
tmp5 = _mm_clmulepi64_si128(a, b, 0x01);
tmp6 = _mm_clmulepi64_si128(a, b, 0x11);
tmp4 = _mm_xor_si128(tmp4, tmp5);
tmp5 = _mm_slli_si128(tmp4, 8);
tmp4 = _mm_srli_si128(tmp4, 8);
tmp3 = _mm_xor_si128(tmp3, tmp5);
tmp6 = _mm_xor_si128(tmp6, tmp4);
tmp7 = _mm_srli_epi32(tmp3, 31);
tmp8 = _mm_srli_epi32(tmp6, 31);
tmp3 = _mm_slli_epi32(tmp3, 1);
tmp6 = _mm_slli_epi32(tmp6, 1);
```

Whereas Figure 7 has:

```
__m128i tmp0, tmp1, tmp2, tmp3, tmp4, tmp5, tmp6,
tmp7, tmp8, tmp9, tmp10, tmp11, tmp12;
__m128i XMMMASK = _mm_setr_epi32(0xffffffff, 0x0, 0x0, 0x0);
tmp3 = _mm_clmulepi64_si128(a, b, 0x00);
tmp6 = _mm_clmulepi64_si128(a, b, 0x11);
tmp4 = _mm_shuffle_epi32(a,78);
tmp5 = _mm_shuffle_epi32(b,78);
tmp4 = _mm_xor_si128(tmp4, a);
tmp5 = _mm_xor_si128(tmp5, b);
tmp4 = _mm_clmulepi64_si128(tmp4, tmp5, 0x00);
tmp4 = _mm_xor_si128(tmp4, tmp3);
tmp4 = _mm_xor_si128(tmp4, tmp6);
tmp5 = _mm_slli_si128(tmp4, 8);
tmp4 = _mm_srli_si128(tmp4, 8);
tmp3 = _mm_xor_si128(tmp3, tmp5);
tmp6 = _mm_xor_si128(tmp6, tmp4);
```

Is this mismatch intentional?

**Comment by wangxiao1254** [comment]
Figure 7 is actually the correct implementation. Figure 5 does not correspond to the standard F2k multiplication in AES-GCM. It incldueds bit-reverse I think.

**Comment by joerowell** [comment]
Ah, so ```mul128``` should be changed, then?

**Comment by wangxiao1254** [comment]
I think I already made the change? The current version is the correct version.

**Comment by wangxiao1254** [comment]
OK I think the latest version should be figure 5 without reflection?

**Comment by joerowell** [comment]
Ah: that was the point I was trying to make :) The point I was making was that the multiplication part of ```gfmul``` is the multiplication from Figure 7 (i.e with reflection) whereas the ```mul128``` part appears to be from Figure 5 (i.e without reflection).

**Comment by wangxiao1254** [comment]
mul128 does not do reduction, it outputs f2^{2k}, so nothing to do how the reduction is done. gfmul does reduction by calling mul128 first and then do reduction.

**Comment by joerowell** [comment]
Sorry, my mistake!

**Comment by wangxiao1254** [comment]
I guess one more thing that makes it confusing is that, for non-reduction multiplication (i.e., the first few lines) they use textbook multiplication in figure 5 but karatsuba in figure 7. In practice I think figure 5 is faster..
