### ISSUE TITLE
Conflict between std::bind and bind on macOS

### ISSUE THREAD

**Issue by fabrice102** [emp-toolkit/emp-tool#2]
On macOS, the compiler (llvm) calls `std::bind` instead of `bind` from `sys/socket.h` in `io/net_io_channel.h` (line 48).
There is no warning. But `accept` then hangs forever.

The solution is to replace `bind` by `::bind` (or to not use `using namespace std;`).
See https://stackoverflow.com/questions/10035294/compiling-code-that-uses-socket-function-bind-with-libcxx-fails

Maybe, it would be interesting to also check the return code of `bind` and `listen` (in that case, you actually would get an error message when trying to compile without `::`, as `std::bind` does not return an integer), e.g.:
```
if(::bind(mysocket, (struct sockaddr *)&serv, sizeof(struct sockaddr)) < 0) {
    perror("error: bind");
    exit(1);
}
if(listen(mysocket, 1) < 0) {
    perror("error: listen");
    exit(1);
}
```

**Comment by wangxiao1254** [comment]
Thanks. Could you please do a pull request? I will merge it to the main repo.

**Comment by fabrice102** [comment]
with or without the error management?

**Comment by wangxiao1254** [comment]
With error management. Thanks

**Comment by wangxiao1254** [comment]
Merged.
