### ISSUE TITLE
No copy constructor in `PRP`

### ISSUE THREAD

**Issue by fabrice102** [emp-toolkit/emp-tool#20]
In the class `PRP`, you have a pointer data member that the class owns (the class creates it in the constructor and destroys it in the destructor). In that setting, you should apply the rule of 3 or 5 (http://en.cppreference.com/w/cpp/language/rule_of_three). Currently the following program crashes because of that:

```C++
#include <prp.h>
#include <vector>
#include <string>

int main() {
  char key[16];
  std::vector<char> plain(16, 0);

  PRP prp;
  prp.aes_set_key(key);
  prp.permute_data(&plain[0], 16);

  PRP prp2 = prp;
  prp2.permute_data(&plain[0], 16);
}
```

The pointer `prp.aes` is deleted twice (once because of `prp` and once because of `prp2`). 
In more complex examples, you can get segfaults.

I think there are 3 solutions:

1. do not use a pointer but directly an object: `AES_KEY aes` instead of `AES_KEY *aes`.
2. use a shared pointer `shared_ptr`
3. apply the rule of 5

I think the first solution makes the more sense in this case, but I have not checked the other parts of the code. They may rely on having a pointer.

**Comment by wangxiao1254** [comment]
this should be fixed by now too
