### ISSUE TITLE
Alignment for PRP member functions

### ISSUE THREAD

**Issue by fabrice102** [emp-toolkit/emp-tool#21]
The functions `PRP::aes_set_key` and `PRP::permute_data` require 128-bit-aligned inputs. This is not really an issue but it might be good to add a comment.

For example, the following example will crash:

```C++
#include <prp.h>
#include <vector>
#include <string>

int main() {
  char key[16];
  std::vector<char> plain(17, 0);

  PRP prp;
  prp.aes_set_key(key);
  prp.permute_data(&plain[1], 16);
}
```

Using `std::string` to store binary data (this might arguably be a bad choice to do so, but some frameworks as GRPC do it) does not provide the required alignment on macOS, for example.

**Comment by fabrice102** [comment]
I've seen that you fixed the alignment in the code. Actually, there is a slightly simpler solution than the one you used: using `_mm_loadu_si128` instead of `_mm_load_si128`.

**Comment by wangxiao1254** [comment]
BTW, using PRP on vector is probably anyway a bad idea. Since vector may occupy different segments of memory that are scattered around the memory linked by the pointer.

**Comment by fabrice102** [comment]
I think that since C++03, vector elements are necessarily contiguous: http://en.cppreference.com/w/cpp/container/vector

**Comment by wangxiao1254** [comment]
I see :) Didn't know that!
