### ISSUE TITLE
Thread safety of PRG

### ISSUE THREAD

**Issue by fabrice102** [emp-toolkit/emp-tool#25]
If I am not mistaken, the constructor of https://github.com/emp-toolkit/emp-tool/blob/stable/emp-tool/utils/prg.h is not thread safe when `seed=nullptr`, because of the fields `counter` and `rnd`. Do you plan to write a thread safe version?

The simplest workaround might be to add a boolean parameter `thread_safe` to the constructor. When `thread_safe` is `true`, the constructor does not set nor use `rnd`, and seed the PRG with `std::random_device`.

What do you think?

**Comment by wangxiao1254** [comment]
I have another solution based on RDSEED, maybe I can push that and you can test if it works on MAC.

**Comment by fabrice102** [comment]
Yes, thanks, I can test. You can create a new branch if you don't want to pollute `stable`.

**Comment by fabrice102** [comment]
Actually, maybe counter mode aes is faster than rdrand. I've not looked into details.

**Comment by wangxiao1254** [comment]
That’s what I’m doing, but you need a seed to start, which is what is read from urand.

that instruction provide hardware level randomness directly and is thread safe

Thanks,

Xiao

**Comment by fabrice102** [comment]
Ok. Sorry, I thought you wanted to use rdrand for everything not just the seeding part.

If it's just for the seeding part, as currently, maybe using `random_device` (as it is the case actually, at least when `rnd=nullptr`) is simpler than rdrand. But to get thread safety, you can remove `rnd` altogether and always use `random_device` for the seeding (this can be a flag).

**Comment by fabrice102** [comment]
If you want, I can do a pull request.

**Comment by wangxiao1254** [comment]
If you have a local fix already, then that would be great. Otherwise I can
fix it during the weekend.

**Comment by wangxiao1254** [comment]
I pushed in stable an option with true random. In dev, I pushed a version using rdseed.

random_device is much slower btw, a better practice is probably create some PRGs using rnd before calling multi-thread functions and use pass PRGs to different thread.

**Comment by wangxiao1254** [comment]
Seems that everything on travis is fine. I think using rdseed might be the best option now, and we don't need to worry about mem leak you mentioned in another issue too.

**Comment by fabrice102** [comment]
Yes, the only issue is that sometimes we might not have access to a CPU with `rdseed`. In one of the project I am working one for example, I have it. So maybe, it's better to add a macro to disable `rdseed` and use back `random_device`. For example:

```C++
#ifdef EMP_USE_RANDOM_DEVICE
			block v;
			int * data = (int *)(&v);
			std::random_device rand_div;
			for (size_t i = 0; i < sizeof(block) / sizeof(int); ++i)
				data[i] = rand_div();
			reseed(&v);
#else
			unsigned long long r0, r1;
			_rdseed64_step(&r0);
			_rdseed64_step(&r1);
			block v = makeBlock(r0, r1);
			reseed(&v);
#endif
```

but in any case, not storing a `static PRG *prg`.

**Comment by wangxiao1254** [comment]
Sure make sense. I will make rdseed as default but also provide random
device as option as you suggested.

**Comment by fabrice102** [comment]
Thanks!

**Comment by wangxiao1254** [comment]
I think everything is updated now. I'm closing this issue as well as the other one related. Feel free to reopen/comment if anything does not work.
