### ISSUE TITLE
PRG::random_mpz

### ISSUE THREAD

**Issue by fabrice102** [emp-toolkit/emp-tool#27]
I think there is a memory leak in `PRG::random_mpz`: `data` is allocated via `new` but is not deleted. Furthermore, alignement is not ensured if I'm not mistaken. It might be better to allocate directly blocks of 16 bytes instead of bytes.

By the way, why do you add 16 bytes?

**Comment by fabrice102** [comment]
And `nbytes = (nbits+1)/8` should be changed to `nbytes = (nbits+7)/8`.
And `data[0] %= (1 << (nbits % 8))` is incorrect when `nbits` is a multiple of 8, if I'm not mistaken.

**Comment by wangxiao1254** [comment]
Oops I haven't checked/used this function since merging from peter's code. Let me see what's the problem.
