### ISSUE TITLE
OS X Sierra: use of undeclared identifier 'fmemopen'

### ISSUE THREAD

**Issue by rmatil** [emp-toolkit/emp-tool#29]
Hey all!

I'm currently trying to install this as dependency for [Scapi](https://github.com/cryptobiu/scapi).
However, I'm currently observing the following error:

```
In file included from emp-tool/io/io_channel.h:3:
emp-tool/utils/prg.h:149:14: error: use of undeclared identifier 'fmemopen'; did you mean 'freopen'?
                FILE *fp = fmemopen(data, nbytes+16, "rb");
                           ^~~~~~~~
                           freopen
/usr/include/stdio.h:248:7: note: 'freopen' declared here
FILE    *freopen(const char * __restrict, const char * __restrict,
         ^
```

and then 

```
In file included from emp-tool/io/io_channel.h:3:
emp-tool/utils/prg.h:149:23: error: cannot initialize a parameter of type 'const char *' with an lvalue of
      type 'uint8_t *' (aka 'unsigned char *')
                FILE *fp = fmemopen(data, nbytes+16, "rb");
                                    ^~~~
/usr/include/stdio.h:248:38: note: passing argument to parameter here
FILE    *freopen(const char * __restrict, const char * __restrict,
```

A bit googling directed me to https://github.com/springlobby/lsl/blob/master/src/lslunitsync/image.cpp#L46 where they implement a custom `fmemopen` method. 

However, I'm a bit unsure how to proceed to get this working. 
Could you help me out?

**Comment by wangxiao1254** [comment]
I believe you are not using the latest version of the code, as this function is no longer there.

**Comment by rmatil** [comment]
Hey @wangxiao1254 

Thanks for your quick reply. Yes, this is actually the case, but I'm locked to an older version of your repo due to other dependencies...
Is there a workaround, which would allow me to use it anyway? Something similar as the method I linked in the previous comment, where they stub it entirely?

I may have to add, that I'm trying to compile this on OS X 10.12.6.

**Comment by wangxiao1254** [comment]
You can refer to this pull request. https://github.com/emp-toolkit/emp-tool/pull/1

However, I think a better option would be trying to sync with the main repo; otherwise you may find it hard to incorporate our new malicious protocols to be open sourced soon :)

**Comment by wangxiao1254** [comment]
Hi, I just wanted to follow up and check if everything works out. Please let me know if you still have some issues.
