### ISSUE TITLE
One question about the random machine for compatibility

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-tool#31]
One error I encounter with Travis on `emp-m2pc` is that instruction not supported. I guess it is the random rdseed instruction problem (not sure now, try to confirm).

Now, if I run Travis on `emp-m2pc`, it also automatically git clone `emp-tool`, `emp-m2pc` should be compiled without rdseed. But now it still seems strange.

Any information for your experience in this?

**Comment by weikengchen** [comment]
What I encounter is the same as this. I will try to figure out more details.

https://travis-ci.org/emp-toolkit/emp-m2pc/builds/265439788

**Comment by weikengchen** [comment]
ok! see this pr: https://github.com/emp-toolkit/emp-tool/pull/32

**Comment by wangxiao1254** [comment]
Seems that this is resolved.
