### ISSUE TITLE
a side note on automatic AES check

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-tool#36]
`__AES__` constant would be the best. But it is only for C program. Sadly, we don't have the same thing in `cmake`.

According to the Internet, it is still suggesting checking the `cpuinfo`, 

for Linux,
`cpuid | grep -i aes`
for Mac,
`sysctl -n machdep.cpu | grep -i aes`

`awk` is not necessary. Just not empty (I mean "\n")  is sufficient.

This note is left for future discussion on AES check.

**Comment by wangxiao1254** [comment]
I know. We will have this check on `__AES__` in https://github.com/emp-toolkit/emp-tool/blob/stable/emp-tool/garble/aes.h. As long as the check is done at compilation or pre-compilation time, it is fine.

In this way, cmake will not complain when the platform does not have AES. But the program will complain (at compilation time or run-time, depending on how it is implemented in the end.)

**Comment by weikengchen** [comment]
That is a good idea. Let me try to add a compilation-time check :)

**Comment by wangxiao1254** [comment]
Thanks!

**Comment by weikengchen** [comment]
https://github.com/emp-toolkit/emp-tool/pull/37

Passed Travis! 
See if that is what you look for.
