### ISSUE TITLE
Spurious warning in `plain_circ.h`

### ISSUE THREAD

**Issue by samee** [emp-toolkit/emp-tool#38]
Express installation procedure is producing the following warning (fresh Ubuntu 17.10 install):

```
/home/emptester/emptoolkit/emp-tool/emp-tool/execution/plain_circ.h:104:10: warning: `res’ is used uninitialized in this function [-Wuninitialized]
    return res;
           ^~~
```

Suggested fix. Rewrite this function as follows:

```C++
uint64_t arr[2];
arr[0] = b ? S1 : S0;
arr[1] = this->gid;
gid++;
return *reinterpret_cast<block*>(arr);
```

**Comment by wangxiao1254** [comment]
Thanks, I will update it soon!

**Comment by wangxiao1254** [comment]
Actually, I cannot reproduce this warning on amazon EC2 (16.04). See also travis compilation results https://travis-ci.org/emp-toolkit/emp-tool/jobs/294328442#L1879.

I will try if this is a 17.10-only issue.

**Comment by samee** [comment]
In case it helps:

```
$ gcc --version
gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0

```

**Comment by wangxiao1254** [comment]
Fixed by explicit initialization.
