### ISSUE TITLE
Automatically use random device if CPU does not support RDSEED?

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-tool#44]
So what happens is: Amazon cloud does not support RDSEED.
An automatic detection in CMakeLists.txt to jump to the random device would be highly appreciated. 

Should we use `try_run`?
https://cmake.org/cmake/help/v3.0/command/try_run.html

**Comment by weikengchen** [comment]
#47

**Comment by wangxiao1254** [comment]
FWIW, certain EC2 machines indeed support RDSEED. For example, c4 4xlarge or better instances.

**Comment by weikengchen** [comment]
Good news. I usually use 2xlarge (and tested on it). 

:) After the slowdown of Moore's Law, Intel surely needs to add more instructions to attract AWS to upgrade these old/cheap/okay chips.
