### ISSUE TITLE
Float addition problem

### ISSUE THREAD

**Issue by alexanderzjs** [emp-toolkit/emp-tool#54]
I am not sure if I am testing wrong, but could someone test Float a(24, 9, -3, ALICE) and Float b(24, 9, 1.0, BOB) addition? I alway get 0...

**Comment by wangxiao1254** [comment]
Yes, we are aware that the current version is buggy for some floating point
operations and are working on a new version of a floating point that should
be more robust.

Xiao

**Comment by wangxiao1254** [comment]
A new Float32 is added. It is consistent with the IEEE754 standard.

See https://github.com/emp-toolkit/emp-tool/blob/stable/emp-tool/circuits/float32_circuit.h
and https://github.com/emp-toolkit/emp-tool/blob/stable/test/float32.cpp

**Comment by alexanderzjs** [comment]
> A new Float32 is added. It is consistent with the IEEE754 standard.

Is there any insight on where you guys have the floating number operation circuits? Is it from any hardware synthesis tools or something else?

Thanks for any information on this

**Comment by wangxiao1254** [comment]
Credit to https://encrypto.de/papers/DDKSSZ15.pdf
Will ACK in the code.
