### ISSUE TITLE
Error while running PRG test

### ISSUE THREAD

**Issue by shreyasnbhat** [emp-toolkit/emp-tool#60]
```
ERROR in eb_param_set() at /mnt/e/Downloads/relic/src/eb/relic_eb_param.c,343: invalid value passed as input.
CAUGHT in eb_param_set() at /mnt/e/Downloads/relic/src/eb/relic_eb_param.c,354.
```
I am using Relic 0.4. 

What might be the issue here? Is this a relic version problem?

**Comment by wangxiao1254** [comment]
Please test with the latest version of relic first. Does relic have versions?

**Comment by shreyasnbhat** [comment]
@wangxiao1254 Never mind! It worked. Had some build flags not set I guess. 
And yes relic does have versions.

**Comment by DAHeath** [comment]
Hi @shreyasnbhat, do you recall what build flags you changed to get the prg test to pass? I seem to be replicating the error you've seen here.

Thanks!

**Comment by wangxiao1254** [comment]
@DAHeath can you provide the error message? Did you install relic using the script?

**Comment by DAHeath** [comment]
Hi @wangxiao1254. The error message is exactly identical to the one in the OP. Based on your comment, I realized I needed to be using your readme script (https://github.com/emp-toolkit/emp-readme/blob/master/scripts/install_packages.sh). This resolved the problem.

Thanks!
