### ISSUE TITLE
segfault in ECC test

### ISSUE THREAD

**Issue by benediamond** [emp-toolkit/emp-tool#74]
Hi, thanks for the great work.

After building successfully on OSX Catalina, I get a segfault in the `ecc` test:
```bash
benediamond@Benjamins-MBP emp-tool % ./bin/ecc   
zsh: segmentation fault  ./bin/ecc
```
after doing some digging, it looks like the bad line is the `add_mod` call:
https://github.com/emp-toolkit/emp-tool/blob/42745481b961a20c8eeba15877da98b6f3c77933/test/ecc.cpp#L22
the reason is that `ctx` is default-assigned to `nullptr` here:
https://github.com/emp-toolkit/emp-tool/blob/42745481b961a20c8eeba15877da98b6f3c77933/emp-tool/utils/group_openssl.h#L46-L50
it can be fixed by replacing [line 22](https://github.com/emp-toolkit/emp-tool/blob/42745481b961a20c8eeba15877da98b6f3c77933/test/ecc.cpp#L22) with:
```cpp
    ic = ia.add_mod(ib, G.order, G.bn_ctx);
```
let me know if you'd like me to raise a PR. thanks.

**Comment by wangxiao1254** [comment]
Thank you for pointing the bug. The code has been updated to address this. Also removed the default parameters to enforce a bn_ctx has to be provided.
