### ISSUE TITLE
About communication sizes

### ISSUE THREAD

**Issue by WeiViming** [emp-toolkit/emp-tool#82]
Hello, Xiao Wang, how can I count the communication sizes between two parties? Is the emp-tool support this? Thanks!

**Comment by wangxiao1254** [comment]
See https://github.com/emp-toolkit/emp-tool/blob/master/emp-tool/io/net_io_channel.h#L35

**Comment by wangxiao1254** [comment]
It is the number of bytes **sent** through this channel.

**Comment by WeiViming** [comment]
Thank you :)
