### ISSUE TITLE
Regression regarding ag2pc

### ISSUE THREAD

**Issue by mkskeller** [emp-toolkit/emp-tool#90]
d707eacd02c0579926039c6a1757cddd688a78bd removes `double_block`, which is used in ag2pc, thus breaking the setup in https://github.com/MPC-SoK/frameworks/.

**Comment by wangxiao1254** [comment]
Forgot to update the master branch on ag2pc. I just put a fix to ag2pc.

**Comment by wangxiao1254** [comment]
If ag2pc still does not work over there, feel free to reopen!
