### ISSUE TITLE
Mismatching declaration and definition of `init` function (for `emp::Integer`)

### ISSUE THREAD

**Issue by bsdinis** [emp-toolkit/emp-tool#94]
Current master: `6ec9345`

In `emp-tool/circuits/integer.h`, `init` has the following declaration:

`57: void init(Bit * bits, const bool* b, int length, int party = PUBLIC);`

In `emp-tool/circuits/integer.hpp`, there is this definition:

`124: inline void init(vector<Bit>& bits, const bool* b, int length, int party)`

**Comment by wangxiao1254** [comment]
fixed
