### ISSUE TITLE
Old Bristol's SHA256 is much slower than New Bristol's SHA256

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-tool#96]
I guess these circuits are from Nigel Smart.

New Bristol's SHA256 has 22573 AND gates.
Old Bristol's SHA256 has 90825 AND gates.

This is because the new Bristol circuit uses a result by Steven Goldfeder, who pointed out that the synthesizer is using an inefficient adder. The old Bristol circuit is not updated accordingly.

Maybe we should just remove the SHA256 circuit file for old Bristol in case someone uses it? Since now a developer can and should choose the new one.

**Comment by wangxiao1254** [comment]
the old sha256 is now sha-256-big and the new circuit added. Note that these circuits are also for benchmarking. many old benchmarking are still done using the larger circuit. A protocol using a smaller SHA256 should not claim 4x improvement just because of this :)
